version: '3.1'

services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    tty: true
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: projectdb
    env_file:
      - .env
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  nest:
    container_name: nest
    build: .
    restart: always
    ports:
      - '5001:5001'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: ['node', 'dist/main']

volumes:
  postgres-volume:
